### ISSUE TITLE
Once a phone number is in memory, it seems to ignore the phone number field on a resubmission

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#309] opened 2019-12-07 23:53 UTC
> [Entered phone number. 
> Already exists in system.]
> 
> - Need to CHANGE phone number (for whatever reason, not necessarily because of above)
> 
> Entered NEW phone number [ending 07]
> 
> Next page displays ORIGINAL phone number.
> ![WhatsApp Image 2019-12-07 at 23 39 12](https://user-images.githubusercontent.com/95868/70382013-b732f380-194c-11ea-960a-08e9df7eb74a.jpeg)
> ![WhatsApp Image 2019-12-07 at 23 39 05](https://user-images.githubusercontent.com/95868/70382014-b7cb8a00-194c-11ea-94ae-def32edeaddf.jpeg)
> 
> So once a phone number is in memory, it seems to ignore the phone number field on a resubmission
> 
>

**Comment by aspiers** [comment] 2019-12-08 05:11
I am fairly sure we already have an issue for this

**Comment by aspiers** [comment] 2019-12-08 16:21
Duplicate of #193

**Closed by aspiers** 2019-12-08 16:21 UTC
Labels: backend, bug, frontend, mobile verification, testing
