### ISSUE TITLE
Verifying phone doesn't redirect back to swap offer flow?

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#928] opened 2024-07-02 00:24 UTC
It sounds like we have a bug where clicking `Offer to swap` with an unverified mobile number diverts to the verification flow but forgets to return back to the swap offering:

> „Hi
> 
> How do I know my offer has been made?
> 
> I found a good match and clicked on 'offer to swap'. I was then asked to verify my 'phone number. I did and I received a notification that it had been successfully verified. After this, I was taken straight through to the page listing possible matches again (different ones).
> 
> Before this, I took a screen shot of the possible swap details.
> 
> There was no message or email saying that the offer had been made successfullly. Is it possible to check this, please?
> 
> Regards
> Wendy”

 It should clearly say if a swap has been offered, so I'm pretty sure in this case she needs to click the offer button again.  However we should make it do that automatically.

**Comment by aspiers** [comment] 2024-07-02 00:25
> There was no message or email saying that the offer had been made successfullly. Is it possible to check this, please?

@tdg No need to check, it will clearly say if a swap has been offered (as you already know).  Pretty sure in this case she needs to click the offer button again.

**Comment by baob** [comment] 2024-07-02 07:58
> Pretty sure in this case she needs to click the offer button again.

That's not very helpful though ?

**Comment by aspiers** [comment] 2024-07-02 11:18
> That's not very helpful though ?

Right, that's why I filed this bug.

**Comment by baob** [comment] 2024-07-02 11:46
Also reported as #766 which is not 100% resolved. Given the fix related to #766, this issue might now be considered a dupe of that.

**Comment by tdg** [comment] 2024-07-02 11:57
> Pretty sure in this case she needs to click the offer button again.

They have been presented different swaps, though, so can't simply offer the same swap

**Comment by aspiers** [comment] 2024-07-02 13:54
[**@baob**](https://github.com/baob) commented on [July 2, 2024 12:46 PM](https://github.com/swapmyvote/swapmyvote/issues/928#issuecomment-2202945814 "Tue Jul 02 2024 12:46:07 GMT+0100 - Replied by Github Reply Comments"):
> Also reported as #766 which is not 100% resolved. Given the fix related to #766, this issue might now be considered a dupe of that.

I've been having problems fully understanding #766, but this issue gave me the clue I needed, so I _think_ I understand it now (in which case yes it's a dupe) - but waiting for clarification from @baob.

**Comment by aspiers** [comment] 2024-07-02 13:54
[**@tdg**](https://github.com/tdg) commented on [July 2, 2024 12:57 PM](https://github.com/swapmyvote/swapmyvote/issues/928#issuecomment-2202976534 "Tue Jul 02 2024 12:57:05 GMT+0100 - Replied by Github Reply Comments"):
> > Pretty sure in this case she needs to click the offer button again.
> 
> They have been presented different swaps, though, so can't simply offer the same swap

If the swaps changed in the mean time there's nothing we can realistically do about that, they just have to pick another swap.

**Comment by aspiers** [comment] 2024-07-02 14:39
Duplicate of #766.

**Comment by aspiers** [comment] 2024-07-02 14:40
[**@baob**](https://github.com/baob) commented on [July 2, 2024 12:46 PM](https://github.com/swapmyvote/swapmyvote/issues/928#issuecomment-2202945814 "Tue Jul 02 2024 12:46:07 GMT+0100 - Replied by Github Reply Comments"):
> Also reported as [#766](https://github.com/swapmyvote/swapmyvote/issues/766) which is not 100% resolved. Given the fix related to [#766](https://github.com/swapmyvote/swapmyvote/issues/766)

@baob Which fix is that?

**Closed** 2024-07-02 14:40 UTC
Labels: bug, duplicate

**Comment by baob** [comment] 2024-07-02 15:10
> @baob Which fix is that?

The referenced PR -> https://github.com/swapmyvote/swapmyvote/pull/767
