### ISSUE TITLE
annotate swap options with explanation of benefits

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#667] opened 2022-07-25 12:02 UTC
When there are more than two constituencies, we could add annotations to each swap options displayed, explaining why/how it would benefit the user's preferred and/or willing parties.  This would depend on the constituency of the swap partner, and their willing party.

**Comment by baob** [comment] 2022-07-25 17:47
NOTE: this builds on ideas developed during GE2019 analysis, such as 'effort needed to win'. Probably shouldn't reference that explicitly but we might say "This swap would means Green Party gets a vote in a constituency where they are probably closer to winning" or "This swap helps the Liberal democrats in what looks like a marginal seat" 

We might also want to consider any special wording where BOTH parties involved in the swap look like making a gain. 

The hedging around in that wording is all related to the fact that this is all based on predictions for the next election, and the data for that comes from Electoral Calculus right now.

@tdg @joshr very interested in your feedback/alternate suggestions on the wording above.

**Comment by baob** [comment] 2024-06-09 17:32
Overlaps with #773

**Comment by aspiers** [comment] 2024-06-11 22:38
This was one of the key things Lorelai highlighted and said she'd think about.

**Comment by tdg** [comment] 2024-06-11 22:58
This sounds like a great idea, but do we feel we could write the algorithm to serve these? It sounds simple but I sense could become complicated very quickly. 

We have a wider variety of input than before (polls and TV recommendations), which is a positive and also might introduce complexity. 

Funnily enough it'd be interesting to get the voters' self-description of their predicament, as an annotation, maybe they could select one from a few common scenarios? These could also help us understand use cases and user stories. 

As polls change etc, would the advice change, and would we let people know the advice had changed (for example for a confirmed swap)?

**Comment by aspiers** [comment] 2024-06-19 16:35
Is #816 a duplicate of this, or are there differences?

**Comment by tdg** [comment] 2024-06-19 17:14
They're the same issue I think, with unique good comments on both

**Comment by aspiers** [comment] 2024-06-19 18:07
[**@tdg**](https://github.com/tdg) commented on [Jun 11, 2024, 11:58 PM GMT+1](https://github.com/swapmyvote/swapmyvote/issues/667#issuecomment-2161734522 "2024-06-11T22:58:59Z - Replied by Github Reply Comments"):
> This sounds like a great idea, but do we feel we could write the algorithm to serve these? It sounds simple but I sense could become complicated very quickly.

I don't think it should be too hard.  With the suggestions in #816 and the TV recommendations text we already have, I think we're probably 60-80% of the way there. 

> We have a wider variety of input than before (polls and TV recommendations), which is a positive and also might introduce complexity.

Yes, keeping the explanations simple and concise is the main challenge I think.

> Funnily enough it'd be interesting to get the voters' self-description of their predicament, as an annotation, maybe they could select one from a few common scenarios? These could also help us understand use cases and user stories.

Nice idea!  Filed as #826.

> As polls change etc, would the advice change, and would we let people know the advice had changed (for example for a confirmed swap)?

Before it's confirmed, I don't see the need to proactively highlight the change, since the user will just see the latest up to date info.

Once it's confirmed, isn't the only way of cancelling the swap to delete your account?  Which feels like too much of a corner case to worry about.  (BTW we expressly disable that on election day, but we certainly shouldn't be updating advice on election day anyway!)

**Comment by aspiers** [comment] 2024-06-23 15:26
I've [just suggested](https://github.com/swapmyvote/swapmyvote/issues/816#issuecomment-2185042665) to close either this or #816.

**Comment by baob** [comment] 2024-06-28 06:29
> I've [just suggested](https://github.com/swapmyvote/swapmyvote/issues/816#issuecomment-2185042665) to close either this or #816.

I think every good idea here is either covered by #816 (done) or #826 (in the backlog). Closing.

**Closed by baob** 2024-06-28 06:29 UTC
Labels: enhancement, swap options, needs refinement, UX
